[test]
  node
  engine

  [test:vars]
  ansible_ssh_user=ts
  ansible_ssh_common_args='-o ProxyCommand="ssh -i /opt/keys/tv_id_rsa.pem -W %h:%p -q ts@35.234.23.123"'

  [node]
  test-0 ansible_host=10.88.3.6
  test-1 ansible_host=10.88.3.5
  test-2 ansible_host=10.88.3.4

  [engine]
  test-1 ansible_host=10.88.3.6
  test-2 ansible_host=10.88.3.5


  [redis_servers:children]
  redis-master
  redis-slave

  [redis_servers:vars]
  ansible_ssh_user=ts
  ansible_ssh_common_args='-o ProxyCommand="ssh -i /opt/keys/tv_id_rsa.pem -W %h:%p -q ts@35.234.23.123"'

  [redis-master]
  db-0 ansible_host=10.88.3.6 redis_sentinel=True

  [redis-slave]
  db-1 ansible_host=10.88.3.5 redis_sentinel=True
  db-2 ansible_host=10.88.3.4 redis_sentinel=True

  [cassandra:children]
  db